import { ServiceItem, PortfolioItem, TestimonialItem, TeamMember, MilestoneItem, FAQItem } from './types';

export const AGENCY_INFO = {
  name: 'Corelix Systems',
  tagline: 'Engineering High-Performance Digital Realities',
  description: 'We help businesses grow with professional websites, mobile apps, AI solutiEnd-to-End Capabilitiesons, video production, and digital marketing — all under one roof.',
  email: 'corelixsystem@gmail.com',
  salesEmail: 'corelixsystem@gmail.com',
  phone: '+923360651081',
  headquarters: 'Lahore, Punjab, Pakistan',
  europeanOffice: '30 St Mary Axe, London, EC3A 8EP, United Kingdom',
  workingHours: 'Mon - Fri: 8:00 AM - 6:00 PM PST',
  socials: {
    github: 'https://github.com/corelix-systems',
    linkedin: 'https://linkedin.com/company/corelix-systems',
    twitter: 'https://x.com/corelixsystems',
    youtube: 'https://youtube.com/@corelixsystems',
  },
  stats: [
    { label: 'Projects Shipped', value: '140+' },
    { label: 'Client Satisfaction', value: '100%' },
    { label: 'Global Team Experts', value: '38+' },
    { label: 'Avg ROI for Clients', value: '3.4x' },
  ],
};

export const SERVICES: ServiceItem[] = [
  {
    id: 'video-editing',
    slug: 'video-editing',
    title: 'Video Editing & Motion Graphics',
    badge: 'Creative Media',
    iconName: 'Film',
    image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=900&q=85',
    shortDescription: 'Cinematic edits, motion graphics, and social content that make your brand impossible to ignore.',
    fullDescription: 'We create polished videos that strengthen your brand, capture attention, and communicate your message clearly — from social media content and promotional videos to motion graphics and commercial campaigns.',
    deliverables: [
      'Commercial & Promotional Videos',
      'Social Media Reels & Shorts',
      'YouTube & Podcast Editing',
      'Motion Graphics & Animations',
      'Product & Brand Videos',
      'Professional Sound & Color',
    ],
    technologies: ['Adobe Premiere Pro', 'DaVinci Resolve Studio', 'After Effects', 'Blender 3D', 'Cinema 4D', 'iZotope RX Audio'],
    process: [
      { step: '01', title: 'Plan.', description: 'Understanding your goals and creative direction.' },
      { step: '02', title: 'Create', description: 'Editing, motion, sound, and visual storytelling.' },
      { step: '03', title: 'Refine', description: 'Polishing every detail to match your brand.' },
      { step: '04', title: 'Deliver', description: 'Final videos ready for every platform.' },
    ],
    idealFor: ['Direct-to-Consumer Brands', 'SaaS Product Launches', 'Tech Influencers & Founders', 'Corporate Brand Campaigns'],
    metrics: [
      { label: 'Avg Retention Boost', value: '+72%' },
      { label: 'Render Turnaround', value: '48-72h' },
    ],
  },
  {
    id: 'website-development',
    slug: 'website-development',
    title: 'Website Development',
    badge: 'Next.js & Jamstack',
    iconName: 'Globe',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=85',
    shortDescription: 'Fast, polished websites that build trust, attract customers, and grow with your business.',
    fullDescription: 'We create modern, fast, and professional websites that build trust, showcase your brand, and turn visitors into customers.',
    deliverables: [
      'Business & Corporate Websites',
      'E-commerce Websites',
      'Custom & CMS-Based Websites',
      'Mobile-Friendly Design',
      'SEO & Performance Optimization',
      'Interactive & Modern Experiences',
    ],
    technologies: ['Next.js 15', 'React 19', 'Tailwind CSS', 'TypeScript', 'Sanity.io', 'Shopify Storefront API', 'Vercel Edge'],
    process: [
      { step: '01', title: 'Discover', description: 'Understanding your business, audience, and goals.' },
      { step: '02', title: 'Design', description: 'Creating a clean and engaging experience for your brand.' },
      { step: '03', title: 'Develop', description: 'Building a fast, responsive, and reliable website.' },
      { step: '04', title: 'Launch', description: 'Testing, optimizing, and delivering your website ready for growth.' },
    ],
    idealFor: ['High-Growth Startups', 'Modern B2B SaaS', 'E-commerce Flagships', 'Enterprise Corporate Rebrands'],
    metrics: [
      { label: 'Avg Lighthouse Score', value: '98/100' },
      { label: 'Bounce Rate Reduction', value: '-38%' },
    ],
  },
  {
    id: 'android-development',
    slug: 'android-app-development',
    title: 'Android App Development',
    badge: 'Kotlin & Jetpack',
    iconName: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=900&q=85',
    shortDescription: 'Reliable Android apps that keep customers connected to your business wherever they go.',
    fullDescription: 'We create reliable, user-friendly Android apps that help businesses connect with customers, simplify services, and deliver a smooth mobile experience.',
    deliverables: [
      'Business & Customer Apps',
      'E-commerce & Service Apps',
      'Custom Mobile Applications',
      'Secure Login & User Accounts',
      'Notifications & App Integrations',
      'Google Play Store Launch Support',
    ],
    technologies: ['Kotlin', 'Jetpack Compose', 'Android SDK', 'Coroutines & Flow', 'Retrofit & Ktor', 'Firebase', 'Play Console'],
    process: [
      { step: '01', title: 'Discover', description: 'Understanding your idea, users, and business goals.' },
      { step: '02', title: 'Design', description: 'Creating a simple and engaging mobile experience.' },
      { step: '03', title: 'Develop', description: 'Building a reliable and responsive Android app.' },
      { step: '04', title: 'Launch', description: 'Testing, improving, and preparing your app for the Play Store.' },
    ],
    idealFor: ['On-Demand Services', 'Fintech & Digital Banking', 'IoT & Smart Device Companions', 'Health & Fitness Apps'],
    metrics: [
      { label: 'Target Crash-Free Rate', value: '99.9%' },
      { label: 'Avg Play Store Rating', value: '4.8 ★' },
    ],
  },
  {
    id: 'web-applications',
    slug: 'ui-ux-design',
    title: 'Web Applications',
    badge: 'SaaS & Enterprise',
    iconName: 'Layers',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=85',
    shortDescription: 'Secure SaaS platforms and business tools that turn complex workflows into clear action.',
    fullDescription: 'We build custom web applications that simplify complex business processes, improve productivity, and give your team the tools they need to work smarter..',
    deliverables: [
      'Custom Business Applications',
      'SaaS Platforms & Customer Portals',
      'Admin & Management Dashboards',
      'Online Booking & Business Systems',
      'Secure User Accounts & Permissions',
      'Payment & Third-Party Integrations',
    ],
    technologies: ['Node.js', 'Express', 'PostgreSQL', 'Prisma / Drizzle', 'Redis', 'Docker', 'WebSockets', 'Tailwind'],
    process: [
      { step: '01', title: 'Understand', description: 'We learn about your business, processes, and goals.' },
      { step: '02', title: 'Plan', description: 'We map out the features and experience your application needs.' },
      { step: '03', title: 'Build', description: 'We develop a secure, reliable, and easy-to-use solution.' },
      { step: '04', title: 'Launch & Support', description: 'We test, launch, and help your application stay reliable as your business grows.' },
    ],
    idealFor: ['B2B SaaS Founders', 'Internal Operations Teams', 'Fintech & Trading Platforms', 'Logistics & Dispatch Portals'],
    metrics: [
      { label: 'API Response Latency', value: '<45ms' },
      { label: 'Uptime Guarantee', value: '99.99%' },
    ],
  },
  {
    id: 'ai-solutions',
    slug: 'ai-solutions',
    title: 'AI Solutions & Automation',
    badge: 'Generative AI & LLMs',
    iconName: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=85',
    shortDescription: 'Practical AI automation that saves time, improves service, and helps teams work smarter.',
    fullDescription: 'We use modern AI to automate repetitive tasks, improve customer experiences, and help your team work faster and smarter.',
    deliverables: [
      'AI Chatbots & Virtual Assistants',
      'Business Process Automation',
      'AI-Powered Customer Support',
      'Smart Document & Data Processing',
      'AI Search & Knowledge Solutions',
      'Custom AI Features for Websites & Apps',
    ],
    technologies: ['Google GenAI SDK', 'Gemini Models', 'LangChain', 'pgvector', 'Python', 'FastAPI', 'LlamaIndex'],
    process: [
      { step: '01', title: 'Understand', description: 'We identify where AI can create the most value for your business.' },
      { step: '02', title: 'Plan', description: 'We design a practical AI solution around your goals and needs.' },
      { step: '03', title: 'Build', description: 'We develop and integrate AI features into your existing workflow or product.' },
      { step: '04', title: 'Launch & Improve', description: 'We test, launch, and continuously improve the solution for better results.' },
    ],
    idealFor: ['Healthcare & Legal Tech', 'Customer Support Scaleups', 'E-commerce Recommendation', 'Automated Content Ops'],
    metrics: [
      { label: 'Workflow Hours Saved', value: '65%+' },
      { label: 'Extraction Accuracy', value: '99.4%' },
    ],
  },
  {
    id: 'seo',
    slug: 'seo-digital-marketing',
    title: 'SEO & Online Growth',
    badge: 'Organic Growth',
    iconName: 'TrendingUp',
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=85',
    shortDescription: 'Search strategies that bring qualified visitors to your business and turn visibility into growth.',
    fullDescription: 'We help your business appear higher in search results, attract more visitors, and reach customers who are actively looking for your products or services.',
    deliverables: [
      'SEO Audit & Website Optimization',
      'Keyword Research & Strategy',
      'On-Page SEO & Content Optimization',
      'Technical SEO Improvements',
      'Local SEO & Business Visibility',
      'Performance & Ranking Monitoring',
    ],
    technologies: ['Ahrefs', 'Semrush', 'Google Search Console', 'Screaming Frog', 'Next.js Dynamic Routing', 'Schema.org'],
    process: [
      { step: '01', title: 'Analyze', description: 'We review your website, industry, competitors, and current search performance.' },
      { step: '02', title: 'Plan', description: 'We identify the right keywords and create a clear SEO strategy.' },
      { step: '03', title: 'Optimize', description: 'We improve your website, content, and search visibility.' },
      { step: '04', title: 'Grow', description: 'We track your progress and continuously improve your rankings and results.' },
    ],
    idealFor: ['B2B & B2C Platforms', 'SaaS Seeking Inbound Pipeline', 'Local Multi-Location Brands', 'High-Ticket Service Agencies'],
    metrics: [
      { label: 'Avg Traffic Growth', value: '+285%' },
      { label: 'Page 1 Keyword Capture', value: '88%' },
    ],
  },
];

export const PORTFOLIO_PROJECTS: PortfolioItem[] = [
  {
    id: 'aura-fintech',
    title: 'Shawarma Stop',
    client: 'Shawarma Stop',
    category: 'web-dev',
    categoryLabel: 'Website Development',
    tagline: 'A modern food website designed to showcase the menu and make ordering easy.',
    summary: 'A modern food website designed to showcase the menu, make ordering easy, and give customers a smooth experience on both mobile and desktop.',
    challenge: 'Aura needed to replace a legacy PHP monolith with a sub-second reactive interface capable of rendering real-time market orderbooks, multi-currency wallets, and instant SWIFT/SEPA transfers while adhering to strict SOC-2 compliance.',
    solution: 'Engineered a Next.js App Router frontend powered by WebSockets, distributed Redis cache, and an event-driven Go microservices backend with biometric multi-factor authentication.',
    impactMetrics: [
      { label: 'Monthly Volume', value: '$120M+' },
      { label: 'Transfer Latency', value: '45ms' },
      { label: 'Security Score', value: '100% SOC2' },
    ],
    technologies: ['Next.js 15', 'TypeScript', 'Tailwind CSS', 'PostgreSQL', 'Redis', 'WebSockets', 'Docker'],
    featuredImage: '/projects/project-1.png',
    galleryImages: [
      'https://picsum.photos/seed/aurapay1/800/500',
      'https://picsum.photos/seed/aurapay2/800/500',
      'https://picsum.photos/seed/aurapay3/800/500',
    ],
    testimonial: {
      quote: 'Corelix delivered in 4 months what our internal team estimated would take over a year. The speed and rock-solid reliability of our web app has won us enterprise banking deals.',
      author: 'Marcus Vance',
      role: 'Chief Technology Officer',
      company: 'Aura Financial',
      avatar: 'https://picsum.photos/seed/marcus/200/200',
    },
    liveUrl: 'https://shawarmastop-aliraza-main.vercel.app/',
    featured: true,
  },
  {
    id: 'pulse-fit-android',
    title: 'Blue Ladder Developers',
    client: 'Blue Ladder Developers',
    category: 'web-dev',
    categoryLabel: 'Website Development',
    tagline: 'A professional real estate website designed to showcase properties and highlight services.',
    summary: 'A professional real estate website designed to showcase properties, highlight services, and help potential buyers and clients easily explore available opportunities.',
    challenge: 'The client struggled with Bluetooth disconnections across fragmented Android phone manufacturers and high battery drain during continuous sensor polling.',
    solution: 'Built a native Kotlin app using Jetpack Compose, Kotlin Coroutines, and Foreground WorkManagers with optimized low-energy Bluetooth (BLE) packet batching and local Room database persistence.',
    impactMetrics: [
      { label: 'Active Users', value: '450K+' },
      { label: 'Play Store Rating', value: '4.9 ★' },
      { label: 'Battery Consumption', value: '-42%' },
    ],
    technologies: ['Kotlin', 'Jetpack Compose', 'Room DB', 'Bluetooth LE', 'Firebase Cloud Messaging', 'Material 3'],
    featuredImage: '/projects/project-2.png',
    galleryImages: [
      'https://picsum.photos/seed/pulsefit1/800/500',
      'https://picsum.photos/seed/pulsefit2/800/500',
    ],
    testimonial: {
      quote: 'The Android app is buttery smooth. Corelix solved our Bluetooth connectivity issues completely. Our Play Store reviews skyrocketed to 4.9 stars!',
      author: 'Elena Rostova',
      role: 'VP of Product',
      company: 'Pulse Health',
      avatar: 'https://picsum.photos/seed/elena/200/200',
    },
    liveUrl: 'https://www.blueladderdevelopers.com/',
    featured: true,
  },
  {
    id: 'lumina-ai-legal',
    title: 'ExactFlow',
    client: 'ExactFlow',
    category: 'web-dev',
    categoryLabel: 'Website Development',
    tagline: 'A professional business website built to clearly present services and simplify customer interactions.',
    summary: 'A professional business website built to clearly present services, simplify customer interactions, and create a strong, trustworthy online presence.',
    challenge: 'Attorneys spent 14+ hours manually auditing cross-jurisdictional procurement agreements for non-compliant clauses.',
    solution: 'Implemented a custom RAG (Retrieval Augmented Generation) pipeline with Gemini models and vector embeddings in pgvector, with rigorous citation verification and human-in-the-loop validation.',
    impactMetrics: [
      { label: 'Review Speed', value: '8 Seconds' },
      { label: 'Hours Saved / Wk', value: '180 hrs' },
      { label: 'Extraction Accuracy', value: '99.7%' },
    ],
    technologies: ['Gemini 2.5 Pro', 'Python', 'FastAPI', 'pgvector', 'Next.js 15', 'LangChain'],
    featuredImage: '/projects/project-3.png',
    galleryImages: [
      'https://picsum.photos/seed/lumina1/800/500',
      'https://picsum.photos/seed/lumina2/800/500',
    ],
    testimonial: {
      quote: 'Lumina AI revolutionized our law firm operations. What used to take associates an entire weekend is now flagged in seconds with precision citations.',
      author: 'Jonathan Sterling',
      role: 'Managing Partner',
      company: 'Sterling & Croft LLP',
      avatar: 'https://picsum.photos/seed/jonathan/200/200',
    },
    liveUrl: 'https://www.exactflow.com/',
    featured: true,
  },
  {
    id: 'nexus-cinematic-reel',
    title: 'Nisha Khan',
    client: 'Nisha Khan',
    category: 'web-dev',
    categoryLabel: 'Website Development',
    tagline: 'A clean and modern personal website designed to showcase professional work and build credibility.',
    summary: 'A clean and modern personal website designed to showcase professional work, build credibility, and make it easy for visitors to learn more and get in touch.',
    challenge: 'Nexus needed an unforgettable launch trailer that conveyed futuristic speed, eco-luxury, and acoustic precision across TV broadcast and vertical TikTok formats.',
    solution: 'Handled full post-production in DaVinci Resolve Studio and After Effects, editing a 90-second hero commercial, 6 tailored social cuts, and custom sound design.',
    impactMetrics: [
      { label: 'Total Views', value: '8.4M+' },
      { label: 'Pre-Order Inquiries', value: '14,200+' },
      { label: 'Engagement Rate', value: '12.8%' },
    ],
    technologies: ['DaVinci Resolve', 'Adobe After Effects', 'Blender 3D', 'iZotope RX', 'Color Grading (ACES)'],
    featuredImage: '/projects/project-4.png',
    galleryImages: [
      'https://picsum.photos/seed/nexusev1/800/500',
      'https://picsum.photos/seed/nexusev2/800/500',
    ],
    testimonial: {
      quote: 'The visual rhythm and sound design was cinematic perfection. Our launch video drove thousands of pre-orders on day one.',
      author: 'Chloe Dupont',
      role: 'Head of Brand Marketing',
      company: 'Nexus Mobility',
      avatar: 'https://picsum.photos/seed/chloe/200/200',
    },
    liveUrl: 'https://nishakhan-chi.vercel.app/',
    featured: true,
  },
  {
    id: 'velo-ecommerce-next',
    title: 'My Small Things',
    client: 'My Small Things',
    category: 'web-dev',
    categoryLabel: 'Website Development',
    tagline: 'A warm and user-friendly website designed to showcase products and create a simple shopping experience.',
    summary: 'A warm and user-friendly website designed to showcase products and create a simple, enjoyable shopping experience for customers.',
    challenge: 'A slow Shopify liquid theme was causing 48% mobile bounce rates and sluggish international loading times.',
    solution: 'Architected a headless Next.js 15 site using Tailwind CSS, Shopify Storefront GraphQL, edge caching, and dynamic currency geo-routing.',
    impactMetrics: [
      { label: 'Conversion Rate', value: '+320%' },
      { label: 'Mobile Page Speed', value: '0.6s' },
      { label: 'Lighthouse Score', value: '100/100' },
    ],
    technologies: ['Next.js 15', 'Tailwind CSS', 'Shopify Storefront API', 'Vercel Edge', 'GraphQL', 'Framer Motion'],
    featuredImage: '/projects/project-5.png',
    galleryImages: [
      'https://picsum.photos/seed/velo1/800/500',
      'https://picsum.photos/seed/velo2/800/500',
    ],
    testimonial: {
      quote: 'Our sales tripled immediately upon launching the new site. The speed, aesthetics, and mobile checkout experience are unmatched.',
      author: 'Antoine de Vries',
      role: 'Creative Director',
      company: 'Velo Couture',
      avatar: 'https://picsum.photos/seed/antoine/200/200',
    },
    liveUrl: 'https://mysmallthings.com/',
    featured: false,
  },
  {
    id: 'scale-seo-growth',
    title: 'Aman Traders Floor',
    client: 'Aman Traders Floor',
    category: 'web-dev',
    categoryLabel: 'Website Development',
    tagline: 'A professional flooring business website designed to showcase products and services and build customer trust.',
    summary: 'A professional flooring business website designed to showcase products and services, build customer trust, and make it easy for visitors to get in touch.',
    challenge: 'CloudOps was outranked by older competitors and spending $45k/month on Google PPC with low ROI.',
    solution: 'Designed programmatic landing page systems, resolved deep crawling loops, restructured semantic schema, and acquired 60+ Tier-1 tech publication backlinks.',
    impactMetrics: [
      { label: 'Monthly Search Visits', value: '125K+' },
      { label: 'Keywords on Page 1', value: '180+' },
      { label: 'PPC Ad Spend Saved', value: '$45K/mo' },
    ],
    technologies: ['Ahrefs', 'Next.js SSG', 'Schema.org JSON-LD', 'Google Search Console', 'Semrush'],
    featuredImage: '/projects/peoject-6.png',
    galleryImages: [
      'https://picsum.photos/seed/cloudops1/800/500',
      'https://picsum.photos/seed/cloudops2/800/500',
    ],
    testimonial: {
      quote: 'Corelix transformed organic search into our #1 customer acquisition channel. We cut our paid ads budget while tripling our pipeline.',
      author: 'Sarah Lin',
      role: 'Head of Growth',
      company: 'CloudOps Pro',
      avatar: 'https://picsum.photos/seed/sarah/200/200',
    },
    liveUrl: 'https://amantradersfloor.com/',
    featured: false,
  },
  {
    id: 'zenith-fleet-android',
    title: 'Shoaib Aluminum & Glass',
    client: 'Shoaib Aluminum & Glass',
    category: 'web-dev',
    categoryLabel: 'Website Development',
    tagline: 'A professional business website designed to showcase aluminum and glass services and highlight completed work.',
    summary: 'A professional business website designed to showcase aluminum and glass services, highlight completed work, and help customers easily explore services and get in touch.',
    challenge: 'Drivers frequently experienced connectivity dead zones in rural tunnels, resulting in lost manifest updates and delayed delivery timestamps.',
    solution: 'Engineered a ruggedized Kotlin app featuring automated offline vector tile map caching, local camera OCR barcode scanning, and delta sync algorithms.',
    impactMetrics: [
      { label: 'Deployments', value: '3,500+ Vans' },
      { label: 'Sync Reliability', value: '99.98%' },
      { label: 'Daily Scans Processed', value: '250K+' },
    ],
    technologies: ['Kotlin', 'Android Jetpack', 'Mapbox SDK', 'ML Kit Barcode', 'Room SQLite'],
    featuredImage: '/projects/project7.png',
    galleryImages: [
      'https://picsum.photos/seed/zenith1/800/500',
      'https://picsum.photos/seed/zenith2/800/500',
    ],
    testimonial: {
      quote: 'Our fleet drivers love how responsive and bulletproof the application is even in zero-reception zones.',
      author: 'David Meyer',
      role: 'Director of Fleet Ops',
      company: 'Zenith Logistics',
      avatar: 'https://picsum.photos/seed/david/200/200',
    },
    liveUrl: 'https://shoaib-aluminum-glass.vercel.app/',
    featured: false,
  },
];

export const TESTIMONIALS: TestimonialItem[] = [
  {
    id: '1',
    author: 'Marcus Vance',
    role: 'Chief Technology Officer',
    company: 'Aura Financial Technologies',
    avatar: 'https://picsum.photos/seed/marcus/200/200',
    rating: 5,
    content: 'Corelix Systems is hands-down the most capable agency team we have ever partnered with. They transformed our fintech vision into a SOC-2 compliant, sub-50ms web application in record time.',
    serviceCategory: 'Web Applications',
    projectResult: '$120M+ Monthly Volume Processed',
  },
  {
    id: '2',
    author: 'Elena Rostova',
    role: 'VP of Product',
    company: 'Pulse Health Technologies',
    avatar: 'https://picsum.photos/seed/elena/200/200',
    rating: 5,
    content: 'Their Android team resolved hardware BLE connection drops that two prior agencies failed to fix. Their Jetpack Compose design system elevated our app to 4.9 stars on the Play Store.',
    serviceCategory: 'Android App Development',
    projectResult: '450K+ Active App Users',
  },
  {
    id: '3',
    author: 'Jonathan Sterling',
    role: 'Managing Partner',
    company: 'Sterling & Croft LLP',
    avatar: 'https://picsum.photos/seed/jonathan/200/200',
    rating: 5,
    content: 'The custom AI document review engine built by Corelix saves our law practice hundreds of associate hours every single month. The precision, speed, and citation accuracy are phenomenal.',
    serviceCategory: 'AI Solutions',
    projectResult: '180 Hours Saved / Week',
  },
  {
    id: '4',
    author: 'Chloe Dupont',
    role: 'Head of Brand Marketing',
    company: 'Nexus Mobility',
    avatar: 'https://picsum.photos/seed/chloe/200/200',
    rating: 5,
    content: 'From storyboard to final 4K render and social reels, Corelix delivered an electric video campaign for our EV launch. Over 8.4 million views and thousands of customer pre-orders.',
    serviceCategory: 'Video Editing & Motion',
    projectResult: '8.4M+ Video Views & 14K Pre-Orders',
  },
  {
    id: '5',
    author: 'Sarah Lin',
    role: 'Head of Growth',
    company: 'CloudOps Pro',
    avatar: 'https://picsum.photos/seed/sarah/200/200',
    rating: 5,
    content: 'Their programmatic SEO framework and technical audit generated over 125,000 monthly organic visits within 6 months. Our customer acquisition cost dropped by more than 60%.',
    serviceCategory: 'Search Engine Optimization',
    projectResult: '+285% Organic Search Inbound',
  },
  {
    id: '6',
    author: 'Antoine de Vries',
    role: 'Creative Director',
    company: 'Velo Couture Paris',
    avatar: 'https://picsum.photos/seed/antoine/200/200',
    rating: 5,
    content: 'Our headless Next.js e-commerce storefront is blazing fast with perfect 100 Lighthouse scores. Our mobile checkout conversion rate increased by over 320% in the first quarter.',
    serviceCategory: 'Website Development',
    projectResult: '+320% Checkout Conversions',
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: '1',
    name: 'Muhammad Ali Raza',
    role: 'Founder & Principal Solutions Architect',
    department: 'Executive & Systems Engineering',
    bio: 'Pioneering distributed software systems, high-concurrency cloud backends, and full-stack digital agency operations with a focus on engineering excellence.',
    avatar: '/ceo/ceo.jpg',
    linkedin: 'https://linkedin.com',
    github: 'https://github.com',
    specialtyBadge: 'Distributed Systems & Architecture',
  },
  {
    id: '2',
    name: 'Alexander Hayes',
    role: 'Head of Frontend & UI Engineering',
    department: 'Web Engineering',
    bio: 'Specialist in Next.js 15, micro-frontend architectures, performance profiling, and accessible design system implementations.',
    avatar: 'https://picsum.photos/seed/alexander/300/300',
    linkedin: 'https://linkedin.com',
    github: 'https://github.com',
    specialtyBadge: 'Next.js & Web Performance',
  },
  {
    id: '3',
    name: 'Devon Vance',
    role: 'Lead Android & Mobile Architect',
    department: 'Mobile Engineering',
    bio: 'Veteran Android engineer specializing in Kotlin, Jetpack Compose, BLE telemetry, and low-latency offline data sync.',
    avatar: 'https://picsum.photos/seed/devon/300/300',
    github: 'https://github.com',
    specialtyBadge: 'Native Android & Jetpack',
  },
  {
    id: '4',
    name: 'Dr. Evelyn Morales',
    role: 'Chief AI Research & LLM Engineer',
    department: 'Artificial Intelligence',
    bio: 'Ph.D. in Computer Science with focus on multimodal reasoning, RAG architectures, prompt evaluation pipelines, and fine-tuning.',
    avatar: 'https://picsum.photos/seed/evelyn/300/300',
    linkedin: 'https://linkedin.com',
    specialtyBadge: 'Gemini Models & RAG Systems',
  },
  {
    id: '5',
    name: 'Julian Croft',
    role: 'Creative Director & Post-Production Lead',
    department: 'Creative & Video Studio',
    bio: 'Award-winning video editor and 3D motion designer with 10+ years directing high-impact commercials, brand films, and viral short-form media.',
    avatar: 'https://picsum.photos/seed/julian/300/300',
    twitter: 'https://x.com',
    specialtyBadge: 'DaVinci Resolve & 3D Motion',
  },
  {
    id: '6',
    name: 'Sophia Patel',
    role: 'Director of Search & Growth Strategy',
    department: 'SEO & Growth Analytics',
    bio: 'Technical SEO strategist who has scaled dozens of SaaS platforms from zero to hundreds of thousands of organic organic visitors.',
    avatar: 'https://picsum.photos/seed/sophia/300/300',
    linkedin: 'https://linkedin.com',
    specialtyBadge: 'Programmatic SEO & Schema',
  },
];

export const MILESTONES: MilestoneItem[] = [
  {
    year: '2020',
    title: 'Corelix Systems Founded',
    description: 'Started as a high-end boutique software engineering consultancy helping Silicon Valley startups scale cloud backends.',
    stat: 'Founded in SF',
  },
  {
    year: '2022',
    title: 'Expansion into Full-Service Mobile & Media',
    description: 'Launched our dedicated Android and Creative Video studios to deliver end-to-end digital transformation for mid-market enterprises.',
    stat: '40+ Projects Shipped',
  },
  {
    year: '2024',
    title: 'AI Lab & European Office Launch',
    description: 'Pioneered custom Gemini AI agent architectures and inaugurated our European hub in London to support international enterprise clients.',
    stat: 'Opened London Hub',
  },
  {
    year: '2026',
    title: 'Global High-Performance Agency',
    description: 'Surpassed 140+ deployed systems with a 100% client satisfaction score across North America, Europe, and Asia-Pacific.',
    stat: '140+ Deployments',
  },
];

export const WHY_CHOOSE_US = [
  {
    title: 'Built to Grow With Your Business',
    description: 'We build reliable digital solutions that are made to support your business as it grows. From the first launch to future improvements, we focus on quality, security, and a smooth experience that you can depend on.',
    icon: 'ShieldCheck',
    badge: 'Enterprise Rigor',
  },
  {
    title: 'Fast, Clear, and Reliable Delivery',
    description: 'We work in focused stages with clear goals and regular updates, so you always know what we’re working on and what comes next. You can easily communicate with our team, review progress, and see your project take shape every step of the way.',
    icon: 'Zap',
    badge: 'Rapid Time-to-Market',
  },
  {
    title: 'Smart AI Solutions for Your Business',
    description: 'We use the latest AI technology to create smarter products, automate everyday tasks, and help your business work more efficiently. Our AI solutions are designed to deliver real value today while helping your business stay ready for the future.',
    icon: 'Cpu',
    badge: 'Cutting-Edge Tech',
  },
  {
    title: 'Focused on Real Business Results',
    description: 'We focus on results that make a real difference to your business — more customers, better online visibility, improved performance, and increased growth. Every project is built with clear goals so you can see the value our work brings to your business.',
    icon: 'TrendingUp',
    badge: 'Business Impact',
  },
];

export const FAQS: FAQItem[] = [
  {
    category: 'General',
    question: 'How quickly can you start our project?',
    answer: 'We can typically start your project within 1–2 business days after discussing your requirements and finalizing the project plan.',
  },
  {
    category: 'General',
    question: 'What engagement options do you offer?',
    answer: 'We offer flexible options to suit your needs, including one-time projects, ongoing support, and dedicated team services.',
  },
  {
    category: 'Services',
    question: 'Do you offer ongoing support after launch?',
    answer: 'Yes. We provide ongoing maintenance and support to keep your website, app, or digital solution secure, up to date, and running smoothly.',
  },
  {
    category: 'Services',
    question: 'Who owns the work after the project is completed?',
    answer: 'You retain full ownership of the work we create for you, including the source code, designs, and project assets, once the final payment is completed.',
  },
  {
    category: 'Pricing',
    question: 'What is your typical project budget?',
    answer: 'Project costs depend on the service and requirements. We offer flexible pricing for different business needs, from smaller projects to larger, custom solutions. Contact us to discuss your project and get a tailored quote.',
  },
  {
    category: 'Workflow',
    question: 'How do you keep clients updated during a project?',
    answer: 'We keep communication clear and consistent with regular progress updates, direct communication with our team, and project reviews so you always know what’s happening.',
  },
];
